services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ems_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin_password
        MONGO_INITDB_DATABASE: ems_database
        MONGO_INITDB_HOST: database
        MONGO_INITDB_PORT: 27017
    networks:
      - ems_network
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin_password
        MONGO_INITDB_DATABASE: ems_database
    networks:
      - ems_network

networks:
  ems_network:
    driver: bridge
